const list = [
   {
      "name":"New Year's Day",
      "dateISO":"2020-01-01",
      "date":{
         "year":2020,
         "month":1,
         "day":1
      }
   },
   {
      "name":"Guru Govind Singh Jayanti",
      "dateISO":"2020-01-02",
      "date":{
         "year":2020,
         "month":1,
         "day":2
      }
   },
   {
      "name":"Lohri",
      "dateISO":"2020-01-14",
      "date":{
         "year":2020,
         "month":1,
         "day":14
      }
   },
   {
      "name":"Pongal",
      "dateISO":"2020-01-15",
      "date":{
         "year":2020,
         "month":1,
         "day":15
      }
   },
   {
      "name":"Makar Sankranti",
      "dateISO":"2020-01-15",
      "date":{
         "year":2020,
         "month":1,
         "day":15
      }
   },
   {
      "name":"Chinese New Year",
      "dateISO":"2020-01-25",
      "date":{
         "year":2020,
         "month":1,
         "day":25
      }
   },
   {
      "name":"Republic Day",
      "dateISO":"2020-01-26",
      "date":{
         "year":2020,
         "month":1,
         "day":26
      }
   },
   {
      "name":"Vasant Panchami",
      "dateISO":"2020-01-30",
      "date":{
         "year":2020,
         "month":1,
         "day":30
      }
   },
   {
      "name":"Guru Ravidas Jayanti",
      "dateISO":"2020-02-09",
      "date":{
         "year":2020,
         "month":2,
         "day":9
      }
   },
   {
      "name":"Valentine's Day",
      "dateISO":"2020-02-14",
      "date":{
         "year":2020,
         "month":2,
         "day":14
      }
   },
   {
      "name":"Maharishi Dayanand Saraswati Jayanti",
      "dateISO":"2020-02-18",
      "date":{
         "year":2020,
         "month":2,
         "day":18
      }
   },
   {
      "name":"Shivaji Jayanti",
      "dateISO":"2020-02-19",
      "date":{
         "year":2020,
         "month":2,
         "day":19
      }
   },
   {
      "name":"Maha Shivaratri/Shivaratri",
      "dateISO":"2020-02-21",
      "date":{
         "year":2020,
         "month":2,
         "day":21
      }
   },
   {
      "name":"Holika Dahana",
      "dateISO":"2020-03-09",
      "date":{
         "year":2020,
         "month":3,
         "day":9
      }
   },
   {
      "name":"Hazarat Ali's Birthday",
      "dateISO":"2020-03-09",
      "date":{
         "year":2020,
         "month":3,
         "day":9
      }
   },
   {
      "name":"Holi",
      "dateISO":"2020-03-10",
      "date":{
         "year":2020,
         "month":3,
         "day":10
      }
   },
   {
      "name":"March Equinox",
      "dateISO":"2020-03-20T09:19:36+05:30",
      "date":{
         "year":2020,
         "month":3,
         "day":20,
         "hour":9,
         "minute":19,
         "second":36
      }
   },
   {
      "name":"Chaitra Sukhladi",
      "dateISO":"2020-03-25",
      "date":{
         "year":2020,
         "month":3,
         "day":25
      }
   },
   {
      "name":"Rama Navami",
      "dateISO":"2020-04-02",
      "date":{
         "year":2020,
         "month":4,
         "day":2
      }
   },
   {
      "name":"Mahavir Jayanti",
      "dateISO":"2020-04-06",
      "date":{
         "year":2020,
         "month":4,
         "day":6
      }
   },
   {
      "name":"First day of Passover",
      "dateISO":"2020-04-09",
      "date":{
         "year":2020,
         "month":4,
         "day":9
      }
   },
   {
      "name":"Maundy Thursday",
      "dateISO":"2020-04-09",
      "date":{
         "year":2020,
         "month":4,
         "day":9
      }
   },
   {
      "name":"Good Friday",
      "dateISO":"2020-04-10",
      "date":{
         "year":2020,
         "month":4,
         "day":10
      }
   },
   {
      "name":"Easter Day",
      "dateISO":"2020-04-12",
      "date":{
         "year":2020,
         "month":4,
         "day":12
      }
   },
   {
      "name":"Vaisakhi",
      "dateISO":"2020-04-13",
      "date":{
         "year":2020,
         "month":4,
         "day":13
      }
   },
   {
      "name":"Mesadi/Vaisakhadi",
      "dateISO":"2020-04-14",
      "date":{
         "year":2020,
         "month":4,
         "day":14
      }
   },
   {
      "name":"Ambedkar Jayanti",
      "dateISO":"2020-04-14",
      "date":{
         "year":2020,
         "month":4,
         "day":14
      }
   },
   {
      "name":"May Day",
      "dateISO":"2020-05-01",
      "date":{
         "year":2020,
         "month":5,
         "day":1
      }
   },
   {
      "name":"Buddha Purnima/Vesak",
      "dateISO":"2020-05-07",
      "date":{
         "year":2020,
         "month":5,
         "day":7
      }
   },
   {
      "name":"Birthday of Ravindranath",
      "dateISO":"2020-05-07",
      "date":{
         "year":2020,
         "month":5,
         "day":7
      }
   },
   {
      "name":"Mother's Day",
      "dateISO":"2020-05-10",
      "date":{
         "year":2020,
         "month":5,
         "day":10
      }
   },
   {
      "name":"Jamat Ul-Vida",
      "dateISO":"2020-05-22",
      "date":{
         "year":2020,
         "month":5,
         "day":22
      }
   },
   {
      "name":"Ramzan Id/Eid-ul-Fitar",
      "dateISO":"2020-05-25",
      "date":{
         "year":2020,
         "month":5,
         "day":25
      }
   },
   {
      "name":"Ramzan Id/Eid-ul-Fitar",
      "dateISO":"2020-05-25",
      "date":{
         "year":2020,
         "month":5,
         "day":25
      }
   },
   {
      "name":"June Solstice",
      "dateISO":"2020-06-21T03:13:40+05:30",
      "date":{
         "year":2020,
         "month":6,
         "day":21,
         "hour":3,
         "minute":13,
         "second":40
      }
   },
   {
      "name":"Father's Day",
      "dateISO":"2020-06-21",
      "date":{
         "year":2020,
         "month":6,
         "day":21
      }
   },
   {
      "name":"Rath Yatra",
      "dateISO":"2020-06-23",
      "date":{
         "year":2020,
         "month":6,
         "day":23
      }
   },
   {
      "name":"Guru Purnima",
      "dateISO":"2020-07-05",
      "date":{
         "year":2020,
         "month":7,
         "day":5
      }
   },
   {
      "name":"Bakr Id/Eid ul-Adha",
      "dateISO":"2020-07-31",
      "date":{
         "year":2020,
         "month":7,
         "day":31
      }
   },
   {
      "name":"Friendship Day",
      "dateISO":"2020-08-02",
      "date":{
         "year":2020,
         "month":8,
         "day":2
      }
   },
   {
      "name":"Raksha Bandhan (Rakhi)",
      "dateISO":"2020-08-03",
      "date":{
         "year":2020,
         "month":8,
         "day":3
      }
   },
   {
      "name":"Janmashtami (Smarta)",
      "dateISO":"2020-08-11",
      "date":{
         "year":2020,
         "month":8,
         "day":11
      }
   },
   {
      "name":"Janmashtami",
      "dateISO":"2020-08-12",
      "date":{
         "year":2020,
         "month":8,
         "day":12
      }
   },
   {
      "name":"Independence Day",
      "dateISO":"2020-08-15",
      "date":{
         "year":2020,
         "month":8,
         "day":15
      }
   },
   {
      "name":"Parsi New Year",
      "dateISO":"2020-08-16",
      "date":{
         "year":2020,
         "month":8,
         "day":16
      }
   },
   {
      "name":"Ganesh Chaturthi/Vinayaka Chaturthi",
      "dateISO":"2020-08-22",
      "date":{
         "year":2020,
         "month":8,
         "day":22
      }
   },
   {
      "name":"Muharram/Ashura",
      "dateISO":"2020-08-29",
      "date":{
         "year":2020,
         "month":8,
         "day":29
      }
   },
   {
      "name":"Onam",
      "dateISO":"2020-08-31",
      "date":{
         "year":2020,
         "month":8,
         "day":31
      }
   },
   {
      "name":"September Equinox",
      "dateISO":"2020-09-22T19:00:39+05:30",
      "date":{
         "year":2020,
         "month":9,
         "day":22,
         "hour":19,
         "minute":0,
         "second":39
      }
   },
   {
      "name":"Mahatma Gandhi Jayanti",
      "dateISO":"2020-10-02",
      "date":{
         "year":2020,
         "month":10,
         "day":2
      }
   },
   {
      "name":"Maha Saptami",
      "dateISO":"2020-10-22",
      "date":{
         "year":2020,
         "month":10,
         "day":22
      }
   },
   {
      "name":"Maha Ashtami",
      "dateISO":"2020-10-23",
      "date":{
         "year":2020,
         "month":10,
         "day":23
      }
   },
   {
      "name":"Maha Navami",
      "dateISO":"2020-10-24",
      "date":{
         "year":2020,
         "month":10,
         "day":24
      }
   },
   {
      "name":"Dussehra",
      "dateISO":"2020-10-25",
      "date":{
         "year":2020,
         "month":10,
         "day":25
      }
   },
   {
      "name":"Milad un-Nabi/Id-e-Milad",
      "dateISO":"2020-10-29",
      "date":{
         "year":2020,
         "month":10,
         "day":29
      }
   },
   {
      "name":"Halloween",
      "dateISO":"2020-10-31",
      "date":{
         "year":2020,
         "month":10,
         "day":31
      }
   },
   {
      "name":"Maharishi Valmiki Jayanti",
      "dateISO":"2020-10-31",
      "date":{
         "year":2020,
         "month":10,
         "day":31
      }
   },
   {
      "name":"Karaka Chaturthi (Karva Chauth)",
      "dateISO":"2020-11-04",
      "date":{
         "year":2020,
         "month":11,
         "day":4
      }
   },
   {
      "name":"Naraka Chaturdasi",
      "dateISO":"2020-11-14",
      "date":{
         "year":2020,
         "month":11,
         "day":14
      }
   },
   {
      "name":"Diwali/Deepavali",
      "dateISO":"2020-11-14",
      "date":{
         "year":2020,
         "month":11,
         "day":14
      }
   },
   {
      "name":"Govardhan Puja",
      "dateISO":"2020-11-15",
      "date":{
         "year":2020,
         "month":11,
         "day":15
      }
   },
   {
      "name":"Bhai Duj",
      "dateISO":"2020-11-16",
      "date":{
         "year":2020,
         "month":11,
         "day":16
      }
   },
   {
      "name":"Chhat Puja (Pratihar Sashthi/Surya Sashthi)",
      "dateISO":"2020-11-20",
      "date":{
         "year":2020,
         "month":11,
         "day":20
      }
   },
   {
      "name":"Guru Tegh Bahadur's Martyrdom Day",
      "dateISO":"2020-11-24",
      "date":{
         "year":2020,
         "month":11,
         "day":24
      }
   },
   {
      "name":"Guru Nanak Jayanti",
      "dateISO":"2020-11-30",
      "date":{
         "year":2020,
         "month":11,
         "day":30
      }
   },
   {
      "name":"First Day of Hanukkah",
      "dateISO":"2020-12-11",
      "date":{
         "year":2020,
         "month":12,
         "day":11
      }
   },
   {
      "name":"Last day of Hanukkah",
      "dateISO":"2020-12-18",
      "date":{
         "year":2020,
         "month":12,
         "day":18
      }
   },
   {
      "name":"December Solstice",
      "dateISO":"2020-12-21T15:32:19+05:30",
      "date":{
         "year":2020,
         "month":12,
         "day":21,
         "hour":15,
         "minute":32,
         "second":19
      }
   },
   {
      "name":"Christmas Eve",
      "dateISO":"2020-12-24",
      "date":{
         "year":2020,
         "month":12,
         "day":24
      }
   },
   {
      "name":"Christmas",
      "dateISO":"2020-12-25",
      "date":{
         "year":2020,
         "month":12,
         "day":25
      }
   },
   {
      "name":"New Year's Eve",
      "dateISO":"2020-12-31",
      "date":{
         "year":2020,
         "month":12,
         "day":31
      }
   }
];

module.exports = list;